# Generated by Django 5.1.1 on 2025-01-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount_completed_offers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='time_of_work',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='work_hours',
            field=models.IntegerField(default=0),
        ),
    ]
