# Generated by Django 5.1.1 on 2025-01-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work_hours',
            field=models.FloatField(),
        ),
    ]
