# Generated by Django 5.1.1 on 2025-01-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_user_work_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_offer', models.CharField(max_length=30, unique=True)),
                ('dead_line', models.DateField()),
                ('amount_of_offer', models.IntegerField()),
                ('drowing', models.ImageField(upload_to='drawings/')),
                ('description', models.TextField()),
                ('material', models.CharField(max_length=50)),
                ('order_of_operations', models.TextField()),
            ],
        ),
    ]
