# Generated by Django 5.1.1 on 2025-02-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_offer_expected_time_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='amount_completed_offers',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='work_hours',
            field=models.FloatField(default=0),
        ),
    ]
