# Generated by Django 5.1.1 on 2025-02-05 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_user_amount_completed_offers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_completed', models.PositiveIntegerField()),
                ('completion_date', models.DateField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='app1.offer')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
