# Generated by Django 5.1.1 on 2025-02-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_worklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='spended_hours',
            field=models.FloatField(default=0),
        ),
    ]
