# Generated by Django 5.1.1 on 2025-02-06 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_worklog_spended_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='drowing',
            field=models.FileField(blank=True, null=True, upload_to='drawings/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
